### ISSUE TITLE
Sorry, this problem has occurred again.

### ISSUE THREAD

**Issue by Teeoo** [FaCuZ/laravel-theme#11]
`php artisan theme:widget default`

 Illuminate\Contracts\Filesystem\FileNotFoundException  : File does not exist at path
at /Users/teeoo/Desktop/VueBlog/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:41
    37|         if ($this->isFile($path)) {
    38|             return $lock ? $this->sharedGet($path) : file_get_contents($path);
    39|         }
    40|
  > 41|         throw new FileNotFoundException("File does not exist at path {$path}");
    42|     }
    43|
    44|     /**
    45|      * Get contents of a file with shared access.

  Exception trace:

  1   Illuminate\Filesystem\Filesystem::get()
      /Users/teeoo/Desktop/VueBlog/vendor/facuz/laravel-themes/src/Commands/WidgetGeneratorCommand.php:192

  2   Facuz\Theme\Commands\WidgetGeneratorCommand::getTemplate("widgetClass")
      /Users/teeoo/Desktop/VueBlog/vendor/facuz/laravel-themes/src/Commands/WidgetGeneratorCommand.php:79

  Please use the argument -v to see more details.

**Comment by FaCuZ** [comment]
The correct syntax is: 
```
php artisan theme:widget new_widget name_theme
```
or global:
```
php artisan theme:widget new_widget --global
```
I create an exception for that error: 66e5d608c650f0d14bf156adfbcbaeda146d93f5

**Comment by Teeoo** [comment]
I have submitted this mistake before, why did it appear again?
