### ISSUE TITLE
blade files downloadable as the theme files are all in the public folder

### ISSUE THREAD

**Issue by padders** [FaCuZ/laravel-theme#16]
Hi, 

Not sure if we're doing something wrong, but all the theme files are stored in /public. This means that you can view the source code in the blade files by navigating to them (e.g. http://demo.local/themes/default/layouts/layout.blade.php where demo.local is my test site name)

This doesn't seem great. Is this easily fixable?

![screenshot 2018-12-20 at 15 47 22](https://user-images.githubusercontent.com/15945371/50294920-db14d500-046e-11e9-9944-a213d950b8d6.png)

**Comment by xLink** [comment]
@padders this should be fixable by moving your themes out of the public directory, and changing the config variable to match!

**Comment by C0kkie** [comment]
@xLink Did you solve it? Cuz if i move the folder the css, js, etc wont load
