### ISSUE TITLE
Laravel Mix integration

### ISSUE THREAD

**Issue by paskuale75** [FaCuZ/laravel-theme#17]
Can I use Laravel Mix with this repo ?

**Comment by LarryTX** [comment]
I at least am having terrible difficulties using Mix with it. In particular, I attempted to add a sass directory to the theme\theme_name\assets directory. Mix is giving me all kinds of errors. Researching it, it looks like it may have to do with problems encountered when Mix tries to climb up the path and fails to find the project root when it expects it. At least it appears similar to https://github.com/JeffreyWay/laravel-mix/issues/533, although that's an old issue.
