### ISSUE TITLE
larave 6 : call to undefined function facuz\theme\array_get()

### ISSUE THREAD

**Issue by imajkumar** [FaCuZ/laravel-theme#25]
laravel 6 have this issue
call to undefined function facuz\theme\array_get()

**Comment by imajkumar** [comment]
https://stackoverflow.com/questions/57884285/laravel-6-call-to-undefined-function-facuz-theme-array-get

**Comment by mastrip2** [comment]
I had the same issue. The library isnt compatible beyond 5.7+. You have to update the following files

/vendor/facuz/laravel-themes/src/AssetContainer.php
line 80 & 99 change str_contains to Str::contains

/vendor/facuz/laravel-themes/src/Theme.php
add  use Illuminate\Support\Arr;
line 350, 374, 417, 679, 805, 1143 array_get to Arr::get
line 681, 813 change array_set to Arr::get
line 680 change $response = current($_events->fire($name)); to $response = current($_events->dispatch($name));

**Comment by imajkumar** [comment]
Thanks
