### ISSUE TITLE
jeremeamia/superclosure to opis/closure

### ISSUE THREAD

**Issue by bryandeasis** [FaCuZ/laravel-theme#30]
Hi just wondering if there's any chance for you to switch to opis/closure? 
jeremeamia/superclosure is no longer maintained.

Thank you

**Comment by imajkumar** [comment]
It is very nice package .  I have fork and made some changes according to laravel 7.x . so you can use ..
https://github.com/imajkumar/laravel-theme

**Comment by bryandeasis** [comment]
> It is very nice package . I have fork and made some changes according to laravel 7.x . so you can use ..
> https://github.com/imajkumar/laravel-theme

I'm still using FaCuZ/laravel-theme for my Laravel 7 project... but would there be any difference if I switch it to imajkumar/laravel-theme ?

**Comment by imajkumar** [comment]
FaCuZ/laravel-theme is fine . few changes as per laravel 7.x required i have implemented so have a look changes in  config/theme.php and composer.json .
FaCuZ/laravel-theme is nice package i have used more than 10 application it works fine .

**Comment by bryandeasis** [comment]
ok but your laravel-theme version is not a package yet.

**Comment by imajkumar** [comment]
https://packagist.org/packages/ayra/laravel-themes

**Comment by bryandeasis** [comment]
using it now thanks, let me see if I will encounter errors

**Comment by bryandeasis** [comment]
Please update your Git ReadME for this package

**Comment by imajkumar** [comment]
yes sure .

**Comment by FaCuZ** [comment]
Hi! Sorry for the delay, I haven't been working with Laravel for 2 years. I will try to keep this package up to date. I added @imajkumar changes to the repo. Thanks!
