### ISSUE TITLE
Question: multiple users

### ISSUE THREAD

**Issue by valante** [FaCuZ/laravel-theme#5]
I want to use this package in a multiple users environment, where every user can select a different theme for his personal piece of website. Is this usecase supported, or is the global namespace variable an obstacle to that? I can't quite determine.

Thanks for your time!

**Comment by FaCuZ** [comment]
Hi, the environment variable its optional, you can dynamically define the theme on your controllers: 

~~~php
$theme = 'user_theme'

return Theme::view([
		    'view' => 'index',
		    'theme' => $theme,
		    'layout' => 'layout',
		    'args' => $data
		   ]);
~~~
>All values except `'view'` are optional

**Comment by valante** [comment]
Thank you kindly!
