### ISSUE TITLE
Load another view

### ISSUE THREAD

**Issue by faysalmahamud** [FaCuZ/laravel-theme#6]
I have two views.
Example: 
views
    applications
      create.blade.php
      form.blade.php
How can I load form.blade.php in create.blade.php

 My create.blade.php code is here
 ```
{!! Form::open(array('route' => 'restaurant.store','method'=>'POST')) !!}
     @include('restaurant.form');
 {!! Form::close() !!}
```

This throws the following error.

`View [restaurant.form] not found. (View: /var/www/works/public/themes/default/views/restaurant/form.blade.php)`

Is there any ways to load another view.

**Comment by FaCuZ** [comment]
Hi, I recommend you put the file `form.blade.php` in the `patials` folder and use 
```php
@partial('form')
```

But if for some reason you need to leave it in `view` you can use:
```php
{!! Theme::scope('form')->content() !!}
```

**Comment by faysalmahamud** [comment]
Thanks for you reply. I chose last solutions and it's working fine.

So, the issue is closed.
